exp_name: "my_first_experiment"

# ModelInterface 및 MyModel에 전달될 인자
model_params:
  model_name: "my_model.MyModel"
  loss_name: "ce"
  lr: 0.001
  input_dim: 784     # MyModel.__init__ 으로 전달됨
  hidden_dim: 256    # MyModel.__init__ 으로 전달됨
  num_classes: 10    # MyModel.__init__ 으로 전달됨

# DataInterface 및 MyDataset에 전달될 인자
data_params:
  dataset_name: "my_dataset.MyDataset"
  batch_size: 64
  num_workers: 4
  train_data_path: "./data/mnist/train-images-idx3-ubyte/train-images-idx3-ubyte"
  train_label_path: "./data/mnist/train-labels-idx1-ubyte/train-labels-idx1-ubyte"
  val_data_path: "./data/mnist/t10k-images-idx3-ubyte/t10k-images-idx3-ubyte"
  val_label_path: "./data/mnist/t10k-labels-idx1-ubyte/t10k-labels-idx1-ubyte"

# Trainer 설정
trainer_params:
  max_epochs: 20